const productsTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",
  PRODUCT_LOADING: "PRODUCT_LOADING",
  PRODUCTS_LOADING: "PRODUCTS_LOADING",
};

export default productsTypes;
